# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(choices=[('iphone', 'iphone'), ('SamSung', 'SamSung'), ('Nikon', 'Nikon'), ('Canon', 'Canon')], default='iphone', max_length=255, null=True)),
                ('photography_style', models.CharField(choices=[('Color', 'Color'), ('Black and White', 'Black and White'), ('Portrait', 'Portrait'), ('Landscape', 'Landscape')], default='color', max_length=255, null=True)),
                ('social_status', models.CharField(choices=[('Peasant', 'Peasant'), ('Royalty', 'Royalty'), ('Merchant', 'Merchant'), ('Scholar', 'Scholar')], default='peasant', max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
