# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170620_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
