language: python
python:
  # - "2.7"
  - "3.6"

install:
  
  - pip install -r requirements.pip

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgresql

script: python imagersite/manage.py test --no input

