# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20170702_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='album', to='imager_images.Photo'),
        ),
    ]
