# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 04:12
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20170711_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='user_images'),
        ),
    ]
