# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0007_auto_20170712_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_images'),
        ),
    ]
